This zip file contains all the files necessary to update your Gallery 2 install
from version <?php print $fromVersionTag ?> to version <?php print $toVersionTag ?>.  For full instructions on updating your
Gallery 2 install please refer to the Gallery Codex:

  http://codex.gallery2.org/index.php/Gallery2:Upgrading_to_2.0.x

If you have questions, you can get answers in the Gallery forums:

  http://gallery.sourceforge.net/forums.php

